(exwm-input-set-key (kbd "<XF86AudioRaiseVolume>") 'desktop-environment-volume-increment)
(exwm-input-set-key (kbd "C-c C-t") 'load-theme)
(exwm-input-set-key (kbd "<XF86AudioLowerVolume>") 'desktop-environment-volume-decrement)
(exwm-input-set-key (kbd "<XF86AudioMute>") 'desktop-environment-toggle-mute)
(exwm-input-set-key (kbd "<XF86AudioMicMute>") 'desktop-environment-toggle-microphone-mute)
(exwm-input-set-key (kbd "<XF86MonBrightnessDown>") 'desktop-environment-brightness-decrement-slowly)
(exwm-input-set-key (kbd "<XF86Search>") 'swiper)
(exwm-input-set-key (kbd "<XF86MonBrightnessUp>") 'desktop-environment-brightness-increment-slowly)
(exwm-input-set-key (kbd "s-<return>") 'vterm)
(exwm-input-set-key (kbd "s-a") 'counsel-linux-app)
(exwm-input-set-key (kbd "s-d") 'dmenu)
(exwm-input-set-key (kbd "s-e <return>") 'eshell)
(exwm-input-set-key (kbd "s-e p") 'proced)
(exwm-input-set-key (kbd "s-e g") 'geiser)
(exwm-input-set-key (kbd "s-e r") 'erc)
(exwm-input-set-key (kbd "s-e f") 'elfeed)
(exwm-input-set-key (kbd "s-e t") 'ansi-term)
(exwm-input-set-key (kbd "s-e m") 'emms-play-file)
(exwm-input-set-key (kbd "s-e f") 'elfeed)
(exwm-input-set-key (kbd "s-x") 'counsel-M-x)
(exwm-input-set-key (kbd "s-q") 'ido-kill-buffer)
(exwm-input-set-key (kbd "s-b") 'ivy-switch-buffer)
(exwm-input-set-key (kbd "s-o") 'other-window)
(exwm-input-set-key (kbd "s-f") 'delete-other-windows)
(exwm-input-set-key (kbd "s-z") 'exwm-workspace-move-window)
(exwm-input-set-key (kbd "s-SPC") 'exwm-floating-toggle-floating)
(exwm-input-set-key (kbd "<print>") 'desktop-environment-screenshot)
(display-battery-mode)
(display-time-mode)
(setq desktop-environment-screenshot-directory "~/media/pix/screens") 
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "<backtab>") 'evil-normal-state)
(global-set-key (kbd "C-c n") 'org-insert-subheading)
(global-set-key (kbd "C-c C-a") 'org-agenda)
(global-set-key (kbd "C-c a") 'org-agenda-month-view)
(shell-command (concat "xset r rate 145 "))
(shell-command "setxkbmap -option ctrl:nocaps")
