(exwm-input-set-key (kbd "<XF86AudioRaiseVolume>") 'desktop-environment-volume-increment)
(exwm-input-set-key (kbd "C-c C-t") 'load-theme)
(exwm-input-set-key (kbd "<XF86AudioLowerVolume>") 'desktop-environment-volume-decrement)
(exwm-input-set-key (kbd "<XF86AudioMute>") 'desktop-environment-toggle-mute)
(exwm-input-set-key (kbd "<XF86AudioMicMute>") 'desktop-environment-toggle-microphone-mute)
(exwm-input-set-key (kbd "s-<return>") 'ansi-term)
(exwm-input-set-key (kbd "s-a") 'counsel-linux-app)
(exwm-input-set-key (kbd "s-d") 'dmenu)
(exwm-input-set-key (kbd "s-x") 'counsel-M-x)
(exwm-input-set-key (kbd "s-q") 'ido-kill-buffer)
(exwm-input-set-key (kbd "s-b") 'ivy-switch-buffer)
(exwm-input-set-key (kbd "s-o") 'other-window)
(exwm-input-set-key (kbd "s-f") 'delete-other-windows)
(exwm-input-set-key (kbd "s-z") 'exwm-workspace-move-window) 
(display-battery-mode)
(display-time-mode)
