(shell-command (concat "server-play-with-mpv & "))
(shell-command (concat "xset r rate 145 "))
(which-key-mode)
(shell-command "setxkbmap -option ctrl:nocaps")
(setq-default message-log-max nil)
(kill-buffer "*Messages*")
(setq org-agenda-files '("~/.emacs.d/agenda.org"))
(set-frame-parameter (selected-frame) 'alpha '(85 . 50))
; (add-to-list 'default-frame-alist '(alpha . (85 . 50)))
;(define-key evil-normal-state-map (kbd "C-r") 'evil-scroll-line-up)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "<backtab>") 'evil-normal-state)
