;;WM keys
(load-file "~/.emacs.d/app-launcher.el")
(exwm-input-set-key (kbd "s-a") 'app-launcher-run-app)
(exwm-input-set-key (kbd "<XF86Explorer>") 'ivy-switch-buffer)
(exwm-input-set-key (kbd "<XF86AudioRaiseVolume>") 'desktop-environment-volume-increment)
(exwm-input-set-key (kbd "<XF86AudioLowerVolume>") 'desktop-environment-volume-decrement)
(exwm-input-set-key (kbd "<XF86AudioMute>") 'desktop-environment-toggle-mute)
(exwm-input-set-key (kbd "<XF86AudioMicMute>") 'desktop-environment-toggle-microphone-mute)
(exwm-input-set-key (kbd "<XF86MonBrightnessDown>") 'desktop-environment-brightness-decrement-slowly)
(exwm-input-set-key (kbd "<XF86Search>") 'swiper)
(exwm-input-set-key (kbd "<XF86MonBrightnessUp>") 'desktop-environment-brightness-increment-slowly)
(exwm-input-set-key (kbd "s-<return>") 'ansi-term)
(exwm-input-set-key (kbd "s-d") 'dmenu)
(exwm-input-set-key (kbd "<XF86LaunchA>") 'dmenu)
(exwm-input-set-key (kbd "s-e <return>") 'eshell)
(exwm-input-set-key (kbd "s-e p") 'proced)
(exwm-input-set-key (kbd "s-e g") 'geiser)
(exwm-input-set-key (kbd "s-t")'exwm-layout-toggle-fullscreen)
(exwm-input-set-key (kbd "s-m") 'exwm-layout-toggle-mode-line)
(exwm-input-set-key (kbd "s-e r") 'erc)
(exwm-input-set-key (kbd "s-e f") 'elfeed)
(exwm-input-set-key (kbd "s-e m") 'emms-play-file)
(exwm-input-set-key (kbd "s-e f") 'elfeed)
(exwm-input-set-key (kbd "s-x") 'counsel-M-x)
(exwm-input-set-key (kbd "s-q") 'kill-current-buffer)
(exwm-input-set-key (kbd "s-b") 'ivy-switch-buffer)
(exwm-input-set-key (kbd "s-o") 'other-window)
(exwm-input-set-key (kbd "s-f") 'delete-other-windows)
(exwm-input-set-key (kbd "s-z") 'exwm-workspace-move-window)
(exwm-input-set-key (kbd "s-c") 'exwm-input-release-keyboard)
(exwm-input-set-key (kbd "s-SPC") 'exwm-floating-toggle-floating)
(exwm-input-set-key (kbd "<print>") 'desktop-environment-screenshot)
(display-battery-mode)
(display-time-mode)
(setq desktop-environment-screenshot-directory "~/media/pix/screens") 
(shell-command (concat "xset r rate 145 "))
(shell-command "setxkbmap -option ctrl:nocaps")
(kill-buffer "*Shell Command Output*")
(delete-other-windows)
